### ISSUE TITLE
[Question] Is any list content pulled from other sources?

### ISSUE THREAD

**Issue by T145** [KitsapCreator/pihole-blocklists#4]
Just curious if these are maintained manually or you've been pulling content from any other sources.

If the latter knowing those would be good!

**Comment by ClovisWebDev** [comment]
Hi!
Apologies for taking so long to address this. Yes, there are many domains that are taken from other sources that I find. While I haven't included the sources up until this point, I plan to now that the repo has gotten some decent traction. From this point I plan to include sources, if any, (aside from domains I find myself) in commits going forward.
