### ISSUE TITLE
Invalid domain

### ISSUE THREAD

**Issue by pallebone** [KitsapCreator/pihole-blocklists#5]
Hi there,

Thank you for this list. i noticed an invalid domain(s) on this list during last update:

  [i] Target: https://raw.githubusercontent.com/KitsapCreator/pihole-blocklists/master/scam-spam.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 16936 exact domains and 0 ABP-style domains (ignored 2 non-domain entries)
      Sample of non-domain entries:
        - "https"
        - "myetherwallet.z"

Kind regards
Peter

**Comment by ClovisWebDev** [comment]
Thanks for the heads up! I will be fixing this shortly.

**Comment by ClovisWebDev** [comment]
Fixed with this commit: 096182923549ec6dbeca7bd1f0cc31552241729a

**Comment by pallebone** [comment]
[i] Target: https://raw.githubusercontent.com/KitsapCreator/pihole-blocklists/master/scam-spam.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 16936 exact domains and 0 ABP-style domains (ignored 0 non-domain entries)
  [i] List has been updated
