### ISSUE TITLE
ads list is blocking facebook.com

### ISSUE THREAD

**Issue by RobotToaster** [KitsapCreator/pihole-blocklists#6]
Not sure if this is intended?

**Comment by ClovisWebDev** [comment]
Hi! ads.txt should not be blocking facebook.com in it's entirety. Fixing shortly.

**Comment by ClovisWebDev** [comment]
Ok this should be resolved now. It may take a bit to show up on my CDN, otherwise it should be good to go!

**Comment by RobotToaster** [comment]
Great, thanks.
